name: ucolis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apple_sign_in: ^0.1.0
  assets_audio_player: ^3.0.3+3
  avatar_glow: ^2.0.1
  awesome_dialog: ^2.0.0-nullsafety.1
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  extended_image: ^4.0.0
  firebase: ^9.0.1
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  firebase_storage: ^10.0.1
  flag: ^5.0.0-nullsafety
  flutter_datetime_picker: ^1.5.0
  flutter_easyloading: ^3.0.0
  flutter_facebook_auth: ^3.5.0
  flutter_geofire: ^2.0.0
  flutter_local_notifications: ^5.0.0
  flutter_native_splash: ^1.1.7+1
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^4.1.0
  flutter_socket_io: ^0.6.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.3
  font_awesome_flutter: ^9.0.0
  geolocator: ^7.0.1
  get: ^4.1.2
  google_maps_flutter: ^2.0.2
  google_sign_in: ^5.0.4
  http: ^0.13.1
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0
  loader_overlay: ^2.0.0
  logger: ^1.0.0
  lottie: ^1.0.1
  overlay_screen: ^1.2.0+1
  permission_handler: ^8.1.1
  progress_indicator_button: ^0.0.3
  progress_state_button: ^1.0.3
  provider: ^5.0.0
  rounded_loading_button: ^2.0.5
  rxdart: ^0.26.0
  simple_html_css: ^3.0.1
  sizer: ^2.0.13
  smart_select: ^4.3.2
  socket_io_client: ^1.0.1
  speech_to_text: ^4.2.2
  websafe_svg: ^2.0.0-nullsafety.0

flutter_native_splash:
  color: "#42a5f5"
  image: assets/icon/taxi.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/audio/
    - assets/audio/fr/
    - assets/audio/en/
    - assets/audio/dioula/
    - assets/audio/more/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
